### ISSUE TITLE
Change main font

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/fornever.me#28]
@Minoru says that he doesn't like the font. Maybe I'll need to do something with that.

**Comment by Minoru** [comment]
Since you've opened an issue for that, I might as well try and explain
what I don't like about the font you're currently using, Cuprum.

Its main problem, IMHO, is the narrowness of the characters; that's
especially prominent with inline blocks of monospaced text: while the
heigh of the characters is the same, the difference in width is
*twofold*. I can't say it makes the text unreadable, but it certainly
takes its toll on my ability to read, and on my comfort while doing so.

The second, less severe problem is the thickness of the font. It just
looks like it's slightly emboldened, which, to me, is uncomfortable.

That's all. In conclusion I'd like to stress once again that fixing
this on the user's end is as easy as installing
[Stylish](https://userstyles.org/) and using a simple style that resets
the font to default (which is `sans-serif`):

```
@-moz-document domain(fornever.me) {
  body {
    font-family: none !important;
  }
}
```

So I don't think this is much of an issue at all.

**Comment by ForNeVeR** [comment]
Note that the code samples does not work when you post them by email. That's an interesting fact.

**Comment by ForNeVeR** [comment]
Well, Markdown doesn't work at all.

**Comment by Minoru** [comment]
> Well, Markdown doesn't work at all.

Indeed!

Another point I'm interested in: my email was signed. GitHub doesn't
display it in any way (which doesn't surprise me). But I wonder if *you*
received an email with attachment?

**Comment by Minoru** [comment]
Wow, quotes do work! (Why am I surprised? I've seen this before.)

**Comment by ForNeVeR** [comment]
No, I can see no attachments with any of your messages in my mailbox.

**Comment by Minoru** [comment]
And if I try to edit it, preview doesn't rended Markdown either.

Re attachments: okay, thank you.
